### PR TITLE
Update prerequisites.sh for Fedora

### PR DESCRIPTION
**Pull request by avsej**

### CODE REVIEW

**Comment by avsej** [comment]
@Lazin thanks for fix. Is it good to merge now?

**Comment by Lazin** [comment]
Thanks for the PR, it's good now. There was a problem with newly added Docker image build. Also, I had to update version and changelog. Otherwise, the packagecloud will freak out.

**Comment by avsej** [comment]
Still broken. I wonder why it runs docker steps which declared in `after_success` section, while the build failed.

```
$ python functests/test_search_api.py akumulid/
OK database at "/home/travis/.akumuli" deleted
OK database created, path: /home/travis/.akumuli
Starting server...
Akumulid launch time: 2018-01-04 08:04:23,475567
OK HTTP server started, port: 8181
OK TCP server started, RESP port: 8282, OpenTSDB port: 4242
OK UDP server started, port: 8383
Sending 1000 messages through TCP...
Sending 1000 messages through TCP...
Sending 1000 messages through TCP...
Sending 1000 messages through TCP...
Sending 1000 messages through TCP...
Test #1 - suggest metric name / 2018-01-04 08:04:33,557714
[Errno 104] Connection reset by peer, Retrying in 3 seconds...
[Errno 104] Connection reset by peer, Retrying in 6 seconds...
Stopping server...
OK HTTP server stopped
OK TCP server stopped
OK UDP server stopped
Traceback (most recent call last):
  File "functests/test_search_api.py", line 305, in <module>
    main(sys.argv[1])
  File "functests/test_search_api.py", line 285, in main
    test_suggest_metric()
  File "/home/travis/build/akumuli/Akumuli/build/functests/akumulid_test_tools.py", line 289, in wrapper
    func(*pos, **kv)
  File "/home/travis/build/akumuli/Akumuli/build/functests/akumulid_test_tools.py", line 340, in f_retry
    return f(*args, **kwargs)
  File "functests/test_search_api.py", line 53, in test_suggest_metric
    response = urlopen(queryurl, json.dumps(query))
  File "/opt/python/2.7.14/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/python/2.7.14/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/opt/python/2.7.14/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/opt/python/2.7.14/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/opt/python/2.7.14/lib/python2.7/urllib2.py", line 1228, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/opt/python/2.7.14/lib/python2.7/urllib2.py", line 1201, in do_open
    r = h.getresponse(buffering=True)
  File "/opt/python/2.7.14/lib/python2.7/httplib.py", line 1121, in getresponse
    response.begin()
  File "/opt/python/2.7.14/lib/python2.7/httplib.py", line 438, in begin
    version, status, reason = self._read_status()
  File "/opt/python/2.7.14/lib/python2.7/httplib.py", line 394, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/opt/python/2.7.14/lib/python2.7/socket.py", line 480, in readline
    data = self._sock.recv(self._rbufsize)
socket.error: [Errno 104] Connection reset by peer
The command "python functests/test_search_api.py akumulid/" exited with 1.
```

**Comment by Lazin** [comment]
For some reason, this script randomly fails on Travis-ci. I created the issue - https://github.com/travis-ci/travis-ci/issues/9008. The only thing I can do is to restart the build until it gets fixed, sorry for the spam. The Docker container build starts always, even on test failure, but it gets uploaded only on success.

**Pull request merged**
